name: Docker y AWS

on:
  pull_request:
    branches: [ main ]
    paths:
      - src/**

jobs:
  build:
    name: Docker push and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DH_USUARIO }}
          password: ${{ secrets.DH_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true 
          tags: ${{ secrets.DH_USUARIO }}/fastapi

  aws:
    name: Deploy image to aws
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AMZ_IP }}
        username: ${{ secrets.AMZ_USUARIO }}
        key: ${{ secrets.AMZ_CLAVE }}
        port: 22  # ${{ secrets.PORT }}
        script: |
            sleep 40
            docker stop web && docker rm web
            docker rmi ${{ secrets.DH_USUARIO }}/fastapi
            docker run -d -p 80:8000 --name web ${{ secrets.DH_USUARIO }}/fastapi